### PR TITLE
Allow Deployments In Subdirectory

### LINKED ISSUE #68: As a manager, I want the S3-browser to be deployable and accessible from a '/some_path' URL
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Engineering Node system administration and overall path organization.

### 💪 Motivation

...so that I can the s3-browser can share a domain name with other applications, e.g.

- main web site: https://pds.nasa.gov
- api: https://pds.nasa.gov/api
- s3-browser: https://pds.nasa.gov/data

### 📖 Additional Details

Currently, the application only works if accessible from `/` for example `https://data.pds.nasa.gov`
We would like  to make the application work from a deployment like https://dwfmsppt3a750.cloudfront.net/data/ (in Dev)

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect** 

### ⚙️ Engineering Details

_No response_

### 🎉 I&T

_No response_

### PR DESCRIPTION
**Pull request by eddiesarevalo**
## 🗒️ Summary
Allow deploying the app in sub directories. 
-Added webpack environment variable that will add a string to hard coded paths.
-Added output public path.
-Changed package name.
-Removed unused buckets from bucket list.

## ⚙️ Test Data and/or Report
Run at https://pds-sit.mcp.nasa.gov/data/

## ♻️ Related Issues
fixes #68

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
👍

**Comment by jordanpadams** [comment]
@eddiesarevalo can you help me understand by build 16.x and 18.x are failing? Is this expected? If not, how can we fix this?

**Comment by eddiesarevalo** [comment]
@jordanpadams 

> @eddiesarevalo can you help me understand by build 16.x and 18.x are failing? Is this expected? If not, how can we fix this?

This repository doesn't have tests set up. The build tries to run "npm run test" which doesn't exist. It seems in build 14 it was throwing an error but wasn't detected as a failure.
Screenshot 2024-07-29 at 1 57 49 PM

In 16 and 18 it still throws an error but now its being detected as a failure.
Screenshot 2024-07-29 at 2 01 48 PM

I see two options. Either we make the testing optional with the `--if-present` as in the `build` step or we add a test script that just returns true. Or the third option which if given enough time we could actually implement tests.

**Comment by jordanpadams** [comment]
@eddiesarevalo added `--if-present`

**Pull request merged**
